import { NextResponse } from 'next/server';
import { google } from 'googleapis';
import { auth } from "@/auth";

export async function POST(request) {
  try {
    const session = await auth();
    if (!session || !session.accessToken) {
      return NextResponse.json({ error: 'Not authenticated with Google' }, { status: 401 });
    }

    const body = await request.json();
    const title = body.title || body.playlist_title;
    const video_ids = body.video_ids || body.song_urls;
    
    if (!video_ids || video_ids.length === 0) {
      return NextResponse.json({ error: 'No songs provided' }, { status: 400 });
    }

    const oauth2Client = new google.auth.OAuth2();
    oauth2Client.setCredentials({ access_token: session.accessToken });

    const youtube = google.youtube({ version: 'v3', auth: oauth2Client });

    // 1. Create Playlist
    const playlistResponse = await youtube.playlists.insert({
      part: 'snippet,status',
      requestBody: {
        snippet: {
          title: title || `TagTune - ${new Date().toISOString().split('T')[0]}`,
          description: 'Generated by TagTune'
        },
        status: {
          privacyStatus: 'private'
        }
      }
    });

    const playlistId = playlistResponse.data.id;

    // 2. Insert items sequentially
    let inserted = 0;
    let skipped = [];
    for (const urlOrId of video_ids) {
      if (!urlOrId) continue;
      
      let videoId = urlOrId;
      if (urlOrId.includes('http')) {
        try {
          const urlObj = new URL(urlOrId);
          videoId = urlObj.searchParams.get('v') || urlObj.pathname.split('/').pop();
        } catch (e) {
          skipped.push({ id: urlOrId, reason: 'Invalid URL' });
          continue;
        }
      }

      try {
        await youtube.playlistItems.insert({
          part: 'snippet',
          requestBody: {
            snippet: {
              playlistId: playlistId,
              resourceId: {
                kind: 'youtube#video',
                videoId: videoId
              }
            }
          }
        });
        inserted++;
      } catch (insertErr) {
        const reason = insertErr.errors?.[0]?.reason || insertErr.message || 'Unknown error';
        skipped.push({ id: videoId, reason });
      }
    }

    const playlistUrl = `https://music.youtube.com/playlist?list=${playlistId}`;
    return NextResponse.json({ playlist_url: playlistUrl, inserted, skipped: skipped.length, skipped_details: skipped });
  } catch (err) {
    console.error('Error creating YouTube playlist:', err);
    if (err.code === 401 || (err.errors && err.errors[0]?.reason === 'authError')) {
      return NextResponse.json({ error: 'YouTube token expired. Please login again.' }, { status: 401 });
    }
    return NextResponse.json({ error: 'Failed to push playlist to YouTube' }, { status: 500 });
  }
}
