import express from 'express';
import { google } from 'googleapis';

const router = express.Router();

router.post('/push', async (req, res) => {
  try {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ error: 'Not authenticated with Google' });
    }

    const { title, video_ids } = req.body;
    
    if (!video_ids || video_ids.length === 0) {
      return res.status(400).json({ error: 'No songs provided' });
    }

    const { youtube_access_token } = req.user;

    const oauth2Client = new google.auth.OAuth2();
    oauth2Client.setCredentials({ access_token: youtube_access_token });

    const youtube = google.youtube({ version: 'v3', auth: oauth2Client });

    // 1. Create Playlist
    const playlistResponse = await youtube.playlists.insert({
      part: 'snippet,status',
      requestBody: {
        snippet: {
          title: title || `TagTune - ${new Date().toISOString().split('T')[0]}`,
          description: 'Generated by TagTune'
        },
        status: {
          privacyStatus: 'private'
        }
      }
    });

    const playlistId = playlistResponse.data.id;

    // 2. Insert items sequentially, tracking success/failures
    let inserted = 0;
    let skipped = [];
    for (const urlOrId of video_ids) {
      if (!urlOrId) continue;
      
      let videoId = urlOrId;
      if (urlOrId.includes('http')) {
        try {
          const urlObj = new URL(urlOrId);
          videoId = urlObj.searchParams.get('v') || urlObj.pathname.slice(1);
        } catch (e) {
          console.warn('Could not parse URL:', urlOrId);
          skipped.push({ id: urlOrId, reason: 'Invalid URL' });
          continue;
        }
      }

      try {
        await youtube.playlistItems.insert({
          part: 'snippet',
          requestBody: {
            snippet: {
              playlistId: playlistId,
              resourceId: {
                kind: 'youtube#video',
                videoId: videoId
              }
            }
          }
        });
        inserted++;
      } catch (insertErr) {
        const reason = insertErr.errors?.[0]?.reason || insertErr.message || 'Unknown error';
        console.warn(`Skipping video ${videoId}: ${reason}`);
        skipped.push({ id: videoId, reason });
      }
    }

    console.log(`Playlist created: ${inserted}/${video_ids.length} songs added, ${skipped.length} skipped`);
    const playlistUrl = `https://music.youtube.com/playlist?list=${playlistId}`;
    res.json({ playlist_url: playlistUrl, inserted, skipped: skipped.length, skipped_details: skipped });
  } catch (err) {
    console.error('Error creating YouTube playlist:', err);
    if (err.code === 401 || (err.errors && err.errors[0]?.reason === 'authError')) {
      return res.status(401).json({ error: 'YouTube token expired. Please login again.' });
    }
    res.status(500).json({ error: 'Failed to push playlist to YouTube' });
  }
});

export default router;
